use orbtk::prelude::*;

widget!(MainView);

impl Template for MainView {
    fn template(self, _: Entity, ctx: &mut BuildContext) -> Self {
        self.name("MainView").child(
            Container::new()
                .padding(10)
                .child(
                    Grid::new()
                        .columns(
                            Columns::create()
                                .push(150)
                                .push(25)
                                .push(150)
                                .push(25)
                                .push(150),
                        )
                        .rows(
                            Rows::create()
                                .push(50)
                                .push(50)
                                .push(50)
                                .push(50)
                                .push(50)
                                .push(50)
                                .push(50)
                                .push(50)
                                .push(50)
                                .push(50),
                        )
                        .child(
                            Button::new()
                                .text("Novo")
                                .attach(Grid::column(0))
                                .attach(Grid::row(0))
                                .build(ctx),
                        )
                        .child(
                            Button::new()
                                .text("Salvar")
                                .attach(Grid::column(2))
                                .attach(Grid::row(0))
                                .build(ctx),
                        )
                        .child(
                            Button::new()
                                .text("Carregar")
                                .attach(Grid::column(4))
                                .attach(Grid::row(0))
                                .enabled(false)
                                .build(ctx),
                        )
                        .build(ctx),
                )
                .build(ctx),
        )
    }
}
